
import java.sql.*;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 91985
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lname = new javax.swing.JLabel();
        lsur = new javax.swing.JLabel();
        luser = new javax.swing.JLabel();
        tname = new javax.swing.JTextField();
        tsur = new javax.swing.JTextField();
        tuser = new javax.swing.JTextField();
        lpass = new javax.swing.JLabel();
        lconpass = new javax.swing.JLabel();
        lemail = new javax.swing.JLabel();
        temail = new javax.swing.JTextField();
        lphone = new javax.swing.JLabel();
        tphone = new javax.swing.JTextField();
        lcity = new javax.swing.JLabel();
        lpin = new javax.swing.JLabel();
        tpin = new javax.swing.JTextField();
        lgender = new javax.swing.JLabel();
        rdmale = new javax.swing.JRadioButton();
        rdfemale = new javax.swing.JRadioButton();
        bsubmit = new javax.swing.JButton();
        tcity = new javax.swing.JComboBox<>();
        rdother = new javax.swing.JRadioButton();
        tpass = new javax.swing.JPasswordField();
        tconpass = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registration form");

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Cambria Math", 1, 36)); // NOI18N
        jLabel1.setText("Registration form");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/close2.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(162, 162, 162)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        lname.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lname.setForeground(new java.awt.Color(255, 255, 255));
        lname.setText("Name");

        lsur.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lsur.setForeground(new java.awt.Color(255, 255, 255));
        lsur.setText("Surname");

        luser.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        luser.setForeground(new java.awt.Color(255, 255, 255));
        luser.setText("User ID");

        tname.setBackground(new java.awt.Color(255, 255, 153));
        tname.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        tname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnameActionPerformed(evt);
            }
        });

        tsur.setBackground(new java.awt.Color(255, 255, 153));
        tsur.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        tuser.setBackground(new java.awt.Color(255, 255, 153));
        tuser.setColumns(6);
        tuser.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        lpass.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lpass.setForeground(new java.awt.Color(255, 255, 255));
        lpass.setText("Password");

        lconpass.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lconpass.setForeground(new java.awt.Color(255, 255, 255));
        lconpass.setText("Confirm Password");

        lemail.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lemail.setForeground(new java.awt.Color(255, 255, 255));
        lemail.setText("Email id");

        temail.setBackground(new java.awt.Color(255, 255, 153));
        temail.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        lphone.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lphone.setForeground(new java.awt.Color(255, 255, 255));
        lphone.setText("Phone");

        tphone.setBackground(new java.awt.Color(255, 255, 153));
        tphone.setColumns(10);
        tphone.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        lcity.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lcity.setForeground(new java.awt.Color(255, 255, 255));
        lcity.setText("City");

        lpin.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lpin.setForeground(new java.awt.Color(255, 255, 255));
        lpin.setText("Pincode");

        tpin.setBackground(new java.awt.Color(255, 255, 153));
        tpin.setColumns(6);
        tpin.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        lgender.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lgender.setForeground(new java.awt.Color(255, 255, 255));
        lgender.setText("Gender");

        rdmale.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(rdmale);
        rdmale.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        rdmale.setForeground(new java.awt.Color(255, 255, 255));
        rdmale.setText("Male");

        rdfemale.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(rdfemale);
        rdfemale.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        rdfemale.setForeground(new java.awt.Color(255, 255, 255));
        rdfemale.setText("Female");

        bsubmit.setBackground(new java.awt.Color(102, 153, 255));
        bsubmit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bsubmit.setText("Submit");
        bsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsubmitActionPerformed(evt);
            }
        });

        tcity.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        tcity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mumbai", "Delhi", "Kolkata", "Hydrabad", "Pune", "Nagpur", "Thane", "Amritsar", "Chennai" }));

        rdother.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(rdother);
        rdother.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        rdother.setForeground(new java.awt.Color(255, 255, 255));
        rdother.setText("other");

        tpass.setBackground(new java.awt.Color(255, 255, 153));
        tpass.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        tconpass.setBackground(new java.awt.Color(255, 255, 153));
        tconpass.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        jLabel2.setForeground(new java.awt.Color(255, 255, 102));
        jLabel2.setText("Password must contain 8 character");

        jLabel3.setForeground(new java.awt.Color(255, 255, 51));
        jLabel3.setText("Please enter above password correctly");

        jLabel5.setForeground(new java.awt.Color(255, 255, 51));
        jLabel5.setText("email id must contain special character ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(bsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lsur, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lgender, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(luser, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lpass, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lconpass, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lemail, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lphone, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lcity, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lpin, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rdmale)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdfemale)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdother))
                            .addComponent(tsur, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tname, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tuser, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tpass, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tphone, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tcity, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tpin, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tconpass, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(temail, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lname)
                    .addComponent(tname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lsur)
                    .addComponent(tsur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lgender)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdfemale)
                            .addComponent(rdother)
                            .addComponent(rdmale))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(luser)
                            .addComponent(tuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lpass)
                    .addComponent(tpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lconpass)
                    .addComponent(tconpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lemail)
                    .addComponent(temail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lphone)
                    .addComponent(tphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lcity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lpin)
                    .addComponent(tpin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addComponent(bsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnameActionPerformed

    private void bsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsubmitActionPerformed
        // TODO add your handling code here:
        String password=new String(tpass.getPassword());
        String confirmpassword =new String(tconpass.getPassword());
        String email=new String(temail.getText());
        String phone=new String(tphone.getText());
        String pin=new String(tpin.getText());
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3308/covid","root","");
            String q="insert into register values(?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement pt=con.prepareStatement(q);
            pt.setString(1,tname.getText());
            pt.setString(2,tsur.getText());
            String g="";
            if(rdmale.isSelected()){
                g=rdmale.getText();
            }
            if(rdfemale.isSelected()){
                g=rdfemale.getText();
            }
            if(rdother.isSelected()){
                g=rdother.getText();
            }
            pt.setString(3,g);
            pt.setString(4,tuser.getText());
            pt.setString(5,password);
            pt.setString(6,confirmpassword);
            pt.setString(7,email);
            pt.setString(8,phone);
            pt.setString(10,pin);
            int count=0;
            if(!password.equals(confirmpassword)|| password.length()<8)
            {
                JOptionPane.showMessageDialog(null,"Please enter correct password","ERROR",JOptionPane.ERROR_MESSAGE);
                Loginframe l=new Loginframe();
                count++;
            }
            Pattern check=Pattern.compile("^[a-zA-Z0-9]+[@]{1}+[a-zA-Z0-9]+[ .]{1}+[a-zA-Z0-9]+$",Pattern.CASE_INSENSITIVE);
            if(!check.matcher(email).find())
            {
               JOptionPane.showMessageDialog(null,"Please enter valid emial address","ERROR",JOptionPane.ERROR_MESSAGE);
                Loginframe l=new Loginframe();
                count++;
            }
            if(!Pattern.matches("[0-9]{10}$",phone)){
                JOptionPane.showMessageDialog(null,"Please enter valid phone number","ERROR",JOptionPane.ERROR_MESSAGE);
                count++;
            }
            if(!Pattern.matches("[0-9]{10}$",pin)){
                JOptionPane.showMessageDialog(null,"Please enter valid pincode","ERROR",JOptionPane.ERROR_MESSAGE);
                count++;
            }
            if(count==0){
            String combo="";
            combo=tcity.getSelectedItem().toString();
            pt.setString(9,combo);
            pt.executeUpdate();
            JOptionPane.showMessageDialog(null,"Successfully Registered");
            con.close();  
            }
            
        }
        catch(Exception e){
           JOptionPane.showMessageDialog(null,"Unable to connect Database"); 
        }
        dispose();
    }//GEN-LAST:event_bsubmitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bsubmit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lcity;
    private javax.swing.JLabel lconpass;
    private javax.swing.JLabel lemail;
    private javax.swing.JLabel lgender;
    private javax.swing.JLabel lname;
    private javax.swing.JLabel lpass;
    private javax.swing.JLabel lphone;
    private javax.swing.JLabel lpin;
    private javax.swing.JLabel lsur;
    private javax.swing.JLabel luser;
    private javax.swing.JRadioButton rdfemale;
    private javax.swing.JRadioButton rdmale;
    private javax.swing.JRadioButton rdother;
    private javax.swing.JComboBox<String> tcity;
    private javax.swing.JPasswordField tconpass;
    private javax.swing.JTextField temail;
    private javax.swing.JTextField tname;
    private javax.swing.JPasswordField tpass;
    private javax.swing.JTextField tphone;
    private javax.swing.JTextField tpin;
    private javax.swing.JTextField tsur;
    private javax.swing.JTextField tuser;
    // End of variables declaration//GEN-END:variables
}
