
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author 91985
 */
public class sales extends javax.swing.JFrame {

    /**
     * Creates new form sales
     */
    public sales() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        lsales = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lsalesid = new javax.swing.JLabel();
        lproductc = new javax.swing.JLabel();
        lproductn = new javax.swing.JLabel();
        lquan = new javax.swing.JLabel();
        lrev = new javax.swing.JLabel();
        lsold = new javax.swing.JLabel();
        tsalesid = new javax.swing.JTextField();
        tprodcode = new javax.swing.JTextField();
        tquantity = new javax.swing.JTextField();
        trevenue = new javax.swing.JTextField();
        tsoldby = new javax.swing.JTextField();
        badd = new javax.swing.JButton();
        bupdate = new javax.swing.JButton();
        bclose = new javax.swing.JButton();
        bdelete1 = new javax.swing.JButton();
        comboproductname = new javax.swing.JComboBox<>();
        bsave = new javax.swing.JButton();
        bshowdata = new javax.swing.JButton();
        tnoproduct = new javax.swing.JTextField();
        tcalrev = new javax.swing.JTextField();
        ttprice = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bcalculate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/close2.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lsales.setFont(new java.awt.Font("Century Schoolbook", 1, 36)); // NOI18N
        lsales.setText("SALES");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(404, 404, 404)
                .addComponent(lsales)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(lsales)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sales id", "Product code", "Product name", "Quantity", "Revenue", "Sold by"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        lsalesid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lsalesid.setText("Sales id:");

        lproductc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lproductc.setText("Product code:");

        lproductn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lproductn.setText("Product name:");

        lquan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lquan.setText("Quantity:");

        lrev.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lrev.setText("Revenue:");

        lsold.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lsold.setText("Sold by:");

        tsalesid.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        tsalesid.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        tprodcode.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        tprodcode.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        tquantity.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        tquantity.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        trevenue.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        trevenue.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        tsoldby.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        tsoldby.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        badd.setBackground(new java.awt.Color(102, 153, 255));
        badd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        badd.setText("Add");
        badd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baddActionPerformed(evt);
            }
        });

        bupdate.setBackground(new java.awt.Color(102, 153, 255));
        bupdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bupdate.setText("Update");
        bupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bupdateActionPerformed(evt);
            }
        });

        bclose.setBackground(new java.awt.Color(51, 51, 255));
        bclose.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/back.png"))); // NOI18N
        bclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcloseActionPerformed(evt);
            }
        });

        bdelete1.setBackground(new java.awt.Color(102, 153, 255));
        bdelete1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bdelete1.setText("Delete");
        bdelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdelete1ActionPerformed(evt);
            }
        });

        comboproductname.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        comboproductname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "COVISHEILD", "COVAXIN", "Disposable Mask", "Sanitizer", "Hand Gloves", "Injection", "Cotton", "Alcohol" }));
        comboproductname.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        bsave.setBackground(new java.awt.Color(102, 153, 255));
        bsave.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bsave.setText("Save");
        bsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsaveActionPerformed(evt);
            }
        });

        bshowdata.setBackground(new java.awt.Color(102, 153, 255));
        bshowdata.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bshowdata.setText("Show Data");
        bshowdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bshowdataActionPerformed(evt);
            }
        });

        tnoproduct.setBackground(new java.awt.Color(255, 255, 153));
        tnoproduct.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        tcalrev.setBackground(new java.awt.Color(255, 255, 153));
        tcalrev.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        ttprice.setBackground(new java.awt.Color(255, 255, 153));
        ttprice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Number of Product:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Total Revenue:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Total Price:");

        bcalculate.setBackground(new java.awt.Color(102, 153, 255));
        bcalculate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bcalculate.setText("Calculate");
        bcalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcalculateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bclose, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lrev, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lsold, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lquan, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lproductn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lproductc, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lsalesid, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(badd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tprodcode, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tsalesid, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboproductname, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tquantity, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(trevenue, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tsoldby, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bdelete1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bupdate)))))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tcalrev, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bcalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tnoproduct, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(229, 229, 229)
                        .addComponent(bsave, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bshowdata, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ttprice, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bclose, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lsalesid)
                            .addComponent(tsalesid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tprodcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lproductc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lproductn)
                            .addComponent(comboproductname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tquantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lquan))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(trevenue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lrev))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tsoldby, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lsold))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(badd, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bdelete1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bsave, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bshowdata, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tnoproduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tcalrev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bcalculate, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ttprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bcloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcloseActionPerformed
        Homepage hm=new Homepage();
        hm.setVisible(true);
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_bcloseActionPerformed

    private void baddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baddActionPerformed
        // TODO add your handling code here:
        String combo="";
        combo=comboproductname.getSelectedItem().toString();
        if(tsalesid.getText().equals("")||tprodcode.getText().equals("")||combo.equals("")||tquantity.getText().equals("")||trevenue.getText().equals("")||tsoldby.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please enter all data");
        }
        else
        {
            String Salesdata[]={tsalesid.getText(),tprodcode.getText(),combo,tquantity.getText(),trevenue.getText(),tsoldby.getText()};
            DefaultTableModel tblModel=(DefaultTableModel)jTable1.getModel();
            tblModel.addRow(Salesdata);
            tsalesid.setText("");
            tprodcode.setText("");
            trevenue.setText("");
            tquantity.setText("");
            tsoldby.setText("");
        }
        
    }//GEN-LAST:event_baddActionPerformed

    private void bsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsaveActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tblmodel=(DefaultTableModel)jTable1.getModel();
        if(tblmodel.getRowCount()==0){
            JOptionPane.showMessageDialog(null,"Table is empty!");
        }
        else{
           try{
               Class.forName("com.mysql.jdbc.Driver");
                Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3308/covid","root","");
                for(int i=0;i<tblmodel.getRowCount();i++){
                    String Salesid=tblmodel.getValueAt(i, 0).toString();
                    String Productcode=tblmodel.getValueAt(i, 1).toString();
                    String Productname=tblmodel.getValueAt(i, 2).toString();
                    String Quantity=tblmodel.getValueAt(i, 3).toString();
                    String Revenue=tblmodel.getValueAt(i, 4).toString();
                    String Soldby=tblmodel.getValueAt(i, 5).toString();
                    
                    String query="INSERT into sales values(?,?,?,?,?,?)";
                    PreparedStatement pt=con.prepareStatement(query);
                    pt.setString(1,Salesid);
                    pt.setString(2,Productcode);
                    pt.setString(3,Productname);
                    pt.setString(4,Quantity);
                    pt.setString(5,Revenue);
                    pt.setString(6,Soldby);
                    pt.execute();
                }
                JOptionPane.showMessageDialog(null," Data insert successfully!");
                tblmodel.setRowCount(0);
           }catch(Exception e){
               
           }
        }
    }//GEN-LAST:event_bsaveActionPerformed

    private void bshowdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bshowdataActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3308/covid","root","");
            Statement st=con.createStatement();
            String data="select * from sales";
            ResultSet rs=st.executeQuery(data);
            
            while(rs.next()){
                String Salesid=rs.getString("Salesid");
                String Productcode=rs.getString("Productcode");
                String Productname=rs.getString("Productname");
                String Quantity=rs.getString("Quantity");
                String Revenue=rs.getString("Revenue");
                String Soldby=rs.getString("Soldby");
                String tbdata[]={Salesid,Productcode,Productname,Quantity,Revenue,Soldby};
                DefaultTableModel tblmodel=(DefaultTableModel)jTable1.getModel();
                tblmodel.addRow(tbdata);
                
            }
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_bshowdataActionPerformed

    private void bdelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdelete1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        if(jTable1.getSelectedRowCount() == 1){
            try{
                Class.forName("com.mysql.jdbc.Driver");
          Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3308/covid","root","");
          Statement stat = con.createStatement();
          String salesid;
          salesid=(String)model.getValueAt(jTable1.getSelectedRow(),0);
          String selectQuery = "DELETE from sales where Salesid= '"+salesid+"'";
          boolean rst = stat.execute(selectQuery) ;
          JOptionPane.showMessageDialog(null,"Deleted successfully");
          tsalesid.setText("");
            tprodcode.setText("");
            trevenue.setText("");
            tquantity.setText("");
            tsoldby.setText("");
            model.removeRow(jTable1.getSelectedRow());
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        }
        else{
            JOptionPane.showMessageDialog(this,"Please select row for delete");
        }
    }//GEN-LAST:event_bdelete1ActionPerformed

    private void bupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bupdateActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
          Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3308/covid","root",""); 
          PreparedStatement pt=con.prepareStatement("UPDATE sales SET Salesid=?,Productcode=?,Productname=?,Quantity=?,Revenue=? where Soldby=?");
          
           pt.setString(1,tsalesid.getText());
           pt.setString(2,tprodcode.getText());
           String combox1="";
           combox1= comboproductname.getSelectedItem().toString();
           pt.setString (3, combox1);
           pt.setString(4,tquantity.getText());
           pt.setString(5,trevenue.getText());
           pt.setString(6,tsoldby.getText());
           pt.executeUpdate();
           JOptionPane.showMessageDialog(null,"Update Successful");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Not Updated");
        }
    }//GEN-LAST:event_bupdateActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int index=jTable1.getSelectedRow();
      TableModel model=jTable1.getModel();
      tsalesid.setText(model.getValueAt(index, 0).toString());
      tprodcode.setText(model.getValueAt(index, 1).toString());
      String productname=model.getValueAt(index, 2).toString();
      switch(productname){
          case "COVISHEILD":
              comboproductname.setSelectedIndex(0);
              break;
          case "COVAXIN":
              comboproductname.setSelectedIndex(1);
              break;
          case "Disposable Mask":
              comboproductname.setSelectedIndex(2);
              break;
          case "Sanitizer":
              comboproductname.setSelectedIndex(3);
              break;
          case "Hand Gloves":
              comboproductname.setSelectedIndex(4);
              break;
          case "Injection":
              comboproductname.setSelectedIndex(5);
              break;
          case "Cotton":
              comboproductname.setSelectedIndex(6);
              break;
          case "Alcohol":
             comboproductname.setSelectedIndex(7);
                 
      }
      
     tquantity.setText(model.getValueAt(index, 3).toString());
     trevenue.setText(model.getValueAt(index, 4).toString());
     tsoldby.setText(model.getValueAt(index, 5).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void getSum(){
         int price=0,rev=0,i;
         for( i=0;i<jTable1.getRowCount();i++){
             price = price+ (Integer.parseInt(jTable1.getValueAt(i,5).toString())*Integer.parseInt(jTable1.getValueAt(i,3).toString()));
             rev = rev+ Integer.parseInt(jTable1.getValueAt(i,4).toString());
         }
         ttprice.setText(Integer.toString(price));
         tcalrev.setText(Integer.toString(rev));
         tnoproduct.setText(Integer.toString(i));
     }
    private void bcalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcalculateActionPerformed
        // TODO add your handling code here:
        getSum();
    }//GEN-LAST:event_bcalculateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton badd;
    private javax.swing.JButton bcalculate;
    private javax.swing.JButton bclose;
    private javax.swing.JButton bdelete1;
    private javax.swing.JButton bsave;
    private javax.swing.JButton bshowdata;
    private javax.swing.JButton bupdate;
    private javax.swing.JComboBox<String> comboproductname;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lproductc;
    private javax.swing.JLabel lproductn;
    private javax.swing.JLabel lquan;
    private javax.swing.JLabel lrev;
    private javax.swing.JLabel lsales;
    private javax.swing.JLabel lsalesid;
    private javax.swing.JLabel lsold;
    private javax.swing.JTextField tcalrev;
    private javax.swing.JTextField tnoproduct;
    private javax.swing.JTextField tprodcode;
    private javax.swing.JTextField tquantity;
    private javax.swing.JTextField trevenue;
    private javax.swing.JTextField tsalesid;
    private javax.swing.JTextField tsoldby;
    private javax.swing.JTextField ttprice;
    // End of variables declaration//GEN-END:variables
}
